### ISSUE TITLE
Project may be missing data file referenced in notebooks (example name: sport_articles.csv)

### ISSUE THREAD

**Issue by gbraven-dev** [microsoft/Data-Discovery-Toolkit#13]
Several of the notebooks reference an input file called sports_articles.csv (as an example name) which is supposed to be a CSV formatted file containing a merge of all of the bbcsports text files.   However the project doesn't include this file or provide instructions on how it is or should be generated.  Are their missing instructions or a missing file in the repository?

**Comment by shanepeckham** [comment]
@gbraven-dev - file is here now https://github.com/microsoft/Data-Discovery-Toolkit/blob/main/data/sport_articles.csv
