### ISSUE TITLE
Renaming property name "FileShareName" in vars.sample

### ISSUE THREAD

**Issue by sushaanttb** [microsoft/Data-Discovery-Toolkit#15]
The property name "FileShareName" in vars.sample is misleading as it gives the impression that we have to create a "file share" in ADLS which is not correct as it's actually ADLS's file-system /container name.

It would be very helpful if we can rename the variable name accordingly or have some clear notes about this field on what this actually means.

<img width="571" alt="MicrosoftTeams-image" src="https://github.com/microsoft/Data-Discovery-Toolkit/assets/12629751/3cb76431-1103-41af-8ca7-2de8caa7ec41">

**Comment by katriendg** [comment]
Additionally, in Readme section explaining the requirement for ADLS Gen 2 account, also explain that a Blob storage container matching the name of this FileShareName variable content needs to be created for the Synapse workspace to be correctly mapped to the default Storage account container.
